// <auto-generated />
using System;
using LeetCodePracticeCompanion.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeetCodePracticeCompanion.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219220928_FixConstraintForProblems.Difficulty")]
    partial class FixConstraintForProblemsDifficulty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("LeetCodePracticeCompanion.Api.Models.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("difficulty");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_date");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("interval_days");

                    b.Property<int>("IntervalMonths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("interval_months");

                    b.Property<DateOnly?>("LastSolveDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_solve_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER")
                        .HasColumnName("number");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_problems");

                    b.ToTable("problems", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
